# Generated by Django 4.2.11 on 2024-05-26 10:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('lavozimi', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mijozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('jinsi', models.CharField(max_length=10)),
                ('pasport', models.CharField(max_length=15)),
                ('jshshir', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prokat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berilgan_sanasi', models.DateField()),
                ('qaytish_sanasi', models.DateField()),
                ('kunlar_soni', models.BigIntegerField()),
                ('umumiy_narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montaj', models.BooleanField(default=False)),
                ('xizmat_narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avans', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miqdori', models.IntegerField()),
                ('kunlik_narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ishchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.mijozlar')),
            ],
        ),
        migrations.CreateModel(
            name='Qurilmalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tasnif', models.CharField(max_length=255)),
                ('rasmi', models.CharField(max_length=255)),
                ('holati', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Turlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tamirlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('qurilma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.qurilmalar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='qurilmalar',
            name='tur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.turlar'),
        ),
        migrations.CreateModel(
            name='Qaytarish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qaytarilgan_sana', models.DateField()),
                ('miqdori', models.IntegerField()),
                ('nosozlik', models.CharField(max_length=255)),
                ('summa', models.BigIntegerField()),
                ('prokat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.prokat')),
            ],
        ),
        migrations.AddField(
            model_name='prokat',
            name='qurilma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.qurilmalar'),
        ),
    ]
