# Generated by Django 4.2.11 on 2024-05-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qurilmalar',
            name='rasmi',
            field=models.ImageField(upload_to=''),
        ),
    ]
