# Generated by Django 4.2.11 on 2024-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_qurilmalar_rasmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qurilmalar',
            name='rasmi',
            field=models.ImageField(default='static/img/default.jpg', upload_to=''),
        ),
    ]
