# Generated by Django 4.2.11 on 2024-05-28 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_qurilmalar_rasmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='qurilmalar',
            name='narxi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prokat',
            name='berilgan_sanasi',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='qaytarish',
            name='qaytarilgan_sana',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tamirlash',
            name='sana',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
