# Generated by Django 4.2.11 on 2024-10-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_qurilmalar_narxi_alter_prokat_berilgan_sanasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rasm',
            field=models.ImageField(default='static/img/default.jpg', upload_to=''),
        ),
    ]
